services:
  laminas:
    build: .
    ports:
     - "8080:80"
    volumes:
     - .:/var/www
  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root